service: my-react-template

frameworkVersion: '>=1.0.0 <2.0.0'

provider:
  name: aws
  # Lambda の設定
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: ${opt:region, 'ap-northeast-1'} # Overwrite the default region used. Default is ap-northeast-1
  memorySize: 512
  timeout: 3
  # Lambda の IAM Role
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource: 
        - "arn:aws:s3:::*/*"
        - "arn:aws:dynamodb:*:*:table/*/index/*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:s3:::*"
        - "arn:aws:dynamodb:*:*:table/*"

# Lambda
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true
    environment:
      NODE_ENV: ${opt:stage, 'dev'}

# CloudFormation の記法で定義
resources:
  Resources:
    S3ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: s3-image-bucket-${opt:state, 'dev'}-${self:service}
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${opt:stage, 'dev'}-ApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${opt:stage, 'dev'}-ApiGatewayRestApiRootResourceId
